spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum_api
    username: root
    password: root507075
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*" # * for all metrics


# To access Mysql: mysql -u root -p