global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-forum-job'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["docker.for.mac.host.internal:8080"]
        labels:
          application: "api-forum"